### ISSUE TITLE
能完善一下功能吗？

### ISSUE THREAD

**Issue by golden777** [lifenjoiner/wget-for-windows#1]
wget --bind-dns-address
https://www.gnu.org/software/wget/manual/html_node/Download-Options.html

--header "Host: xxxx.com"  好像也并不会生效

**Comment by lifenjoiner** [comment]
如果我没有理解错的话，你是说对于release里下载的预编译exe文件，`--bind-dns-address`和`--header "Host: xxxx.com"`无效。

`--bind-dns-address`:
如你列出的文档所说`libcares only`。预编译的是没有包含这个库的。有很多可自定义的编译选项，有特殊需要的话请自己编译。`wget -V`可以查看当前的编译选项。

`--header "Host: xxxx.com"`:
`--header`是支持`Host`的。长参数要加`=`。比如：`wget.exe -t 1 -O - --header="Host: example.com" http://www.baidu.com`
