### ISSUE TITLE
wget file size and features

### ISSUE THREAD

**Issue by bovirus** [lifenjoiner/wget-for-windows#11]
@lifenjoiner 

Thanks for you continuos develop about winget.

Could you please describe in details why you exe file size is so smaller (1 MB) then other wget windows exe build and compared with other build are there some feature less in your build?

Like this build (about 5MB) - https://eternallybored.org/misc/wget/releases/

Are some libraries modules not included in your build?

What are the differences about open-sll library and open-sll-lite that you used?

Thanks.

**Comment by lifenjoiner** [comment]
Check `wget -V` to see the features. `+`: have; `-`: do not have.

In short:
1. I implemented new wrappers with Windows native API to replace large libraries: OpenSSL, libidn and etc.
2. Use alternative libraries: winicon to replace libicon.
3. Do not enable optional or rarely used features/libraries: c-ares, GPG, meatalink and etc.

For details, read the `readme.md` and the CI files.

**Comment by bovirus** [comment]
@lifenjoiner 

Thanks for clear explanation.
And thanks to explain that in home page.
