### ISSUE TITLE
wget - By default show on dos capètion the status of wget operation

### ISSUE THREAD

**Issue by bovirus** [lifenjoiner/wget-for-windows#12]
@lifenjoiner 

By default, your wget version, without any specfic option show on dos caption the status of wget operation

Please check screenshot.

![image](https://github.com/user-attachments/assets/5c009839-74ad-4785-aa82-17d065c282da)

Other build of wget didn't do that.

How can disable this option?
How can could disabled by default?
Could you pelase condier to dsiable by defualt this option in future build to have the same appearnce for your build and otehr buidls?

I have sopme batch that use TITLE command and your wget version (compared with other builds) clear the message in dos caption and replace with wget status.

Thanks. Kr.

**Comment by lifenjoiner** [comment]
Fixed by aa0eced.

**Comment by bovirus** [comment]
@lifenjoiner 

Thanks for the fix.
Please when you can build the new version to enable me to test.
Thanks.

**Comment by lifenjoiner** [comment]
https://github.com/lifenjoiner/wget-for-windows/actions/runs/12118575978
