### ISSUE TITLE
wget 2.2.0 - New source

### ISSUE THREAD

**Issue by bovirus** [lifenjoiner/wget-for-windows#13]
@lifenjoiner 

GNU release a new wget source (2.2.0) that is more recente then 1.25.

1.25 - realease date: 10.11.2024
2.2.0 - release date: 24.-11.2024

Have you any plan to release a new build based on this 2.2.0 source?

**Comment by lifenjoiner** [comment]
No. V2 is a completely rewritten version and obviously needs rework. V1 works well for me, for now.
