### ISSUE TITLE
能写一个编译的过程吗？

### ISSUE THREAD

**Issue by 947942434** [lifenjoiner/wget-for-windows#2]
比如写cmake xmake这些工程文件来做夸平台编译工具？
使用wolfssl替换openssl?
主是我想学习一下，移植到我的项目中！但是不想使用mingw来编译！

**Comment by lifenjoiner** [comment]
现有的文档已经很详细完善了。我就是参考它们的。
如果不满意，您完全可以 happy hacking ... 亲自操刀更能出真知。
有了成果回馈出来，社区肯定也非常高兴的~
