### ISSUE TITLE
支持中文网页下载吗

### ISSUE THREAD

**Issue by yunfei2020** [lifenjoiner/wget-for-windows#3]
请问，支持中文网页下载吗

**Comment by lifenjoiner** [comment]
呃……说法太抽象了，没能明白，你自己试一下不久马上知道啦？！

**Comment by yunfei2020** [comment]
我试过了，不支持，只要网页链接里 带中文的，都不能下载

**Comment by lifenjoiner** [comment]
不应该……
这样空谈没有意义，展示你的例子

**Comment by 6uO** [comment]
使用在线解码URL解码%XX%XX%XX为中文（含所有非ASCII），或者加%：%%XX%%XX%%XX
不过保存文件名是编码的，只能-o
