### ISSUE TITLE
Wget WinTLS and Windows XP

### ISSUE THREAD

**Issue by Wilenty** [lifenjoiner/wget-for-windows#5]
Hello.
Wget based on WinTLS does not work on XP as its written in the description (in the releases):
`XP (NT5): WinTLS version is with limited capability due to the OS. It fails if IE can't open the https URL! The system may not have the lowest Cipher Suites that the server requests, nor SNI/CDN! Try OpenSSL version.`

It does not work at all, screenshot:
![wgetWinTLS](https://user-images.githubusercontent.com/61757638/194720074-f8975197-5239-4802-86f5-4d0f55fec922.png)

I have checked the "wget-v1.21.1.147-f4a3d_WinTLS_win32" and "wget-v1.21.3.141-91166_WinTLS_win32". None of them want to work on XP.

Greetings,
Wilenty

**Comment by lifenjoiner** [comment]
Thanks for your report. I didn't notice that. That's just copied from earlier descriptions. And the earlier binaries had been deleted.
I don't use XP anymore, and have added `-D_WIN32_WINNT=0x0600` to `CFLAGS` targeting NT 6.0 and later.
Believe me, without TLS 1.2+ nor SNI supporting (CDN), it is useless in nowadays!
If you really are interested in XP, you may try compile it yourself without that.

**Comment by Wilenty** [comment]
Thank you for checking.
I don't use XP on my work machine, but I have it installed on VM (virtual machine) for testing. I just wanted to inform you that it does not work as described - that's all. And I checked it on XP (on VM), because I saw this:
![Required OS version](https://user-images.githubusercontent.com/61757638/194774016-0249364d-f43b-4544-8259-7207e15d38ff.png)

It's not connected to the main problem, but I saw that it throws output to the error output (STD_ERROR), but for example, the help after `--help` command-line parameter to the normal output (STD_OUTPUT). I don't know if it's intended action, so you can check it if you want.

I can't compile this source in VS2015CE, and I don't found function `GetFinalPathNameByHandleA` in your source. But, I see this function works from Vista on: https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlea
By the way, if you want to make it to work from XP, you can use the `NtQueryObject` instead, which works from W2K: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntqueryobject
And some examples: https://cpp.hotexamples.com/examples/-/-/NtQueryObject/cpp-ntqueryobject-function-examples.html

I used your wget modification to download 7-ZIP repack from there: https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script/blob/main/DownloadWithRename.cmd after suggestion in comments, because it's smaller. But, 7-ZIP works from XP. :)

**Comment by 6uO** [comment]
WinHex or HexEditor or Visual Studio open
Search:`GetFinalPathNameByHandleA`
Modification:`Beep` 00
Should work

**Comment by lifenjoiner** [comment]
1. This is a mod of the upstream https://git.savannah.gnu.org/git/wget.git. So, most behaviors keep the same.
2. It heavily relies on project gnulib. And then, it should (must) be build using MSYS2 + Mingw-w64, AFAIK. If you want to build it yourself, refer my CI file.
3. The PE header values are assigned by GCC automatically. The same result on files of the MSYS2 + Mingw-w64. BTW, some values don't really count.
4. `GetFinalPathNameByHandleA` is introduced by upstream gnulib, as I said. Replace it with `Beep` is not recommended, at your own risk. The 2 functions have different parameters and result.
5. When a lot of infrastructures are out of maintenance, supporting an outdated OS is hard work, no guarantees, just if lucky.

**Comment by 6uO** [comment]
> 4. `GetFinalPathNameByHandleA` is introduced by upstream gnulib, as I said. Replace it with `Beep` is not recommended, at your own risk. The 2 functions have different parameters and result.
确实，不清楚为什么gnulib不动态加载模块和函数（可能会导致开发时出现莫名其妙的问题？），静态直接三八线画死......
> 5. When a lot of infrastructures are out of maintenance, supporting an outdated OS is hard work, no guarantees, just if lucky.
试试VC-LTL

**Comment by lifenjoiner** [comment]
> VC-LTL

As named, it is only for VC but not GCC.

You can know from the above commit that at least `stat-w32.c` of gnulib had been targeting Win8 and assumed at least Vista.
Try ReactOS, maybe.
