### ISSUE TITLE
Info about new version 1.24.5

### ISSUE THREAD

**Issue by bovirus** [lifenjoiner/wget-for-windows#6]
@lifenjoiner 

Hi.
Thanks for new version.
What's the main difference with this version

https://eternallybored.org/misc/wget/

What are the main difference (plus/minus)?
Why so small size of your package (about 0.5MB) then other package (5.1 MB)?

**Comment by lifenjoiner** [comment]
The "About" section has described the main differences from the origin. While others I don't know much. But at least they rely on OpenSSL.
