### ISSUE TITLE
--no-check-certificate不起作用

### ISSUE THREAD

**Issue by 6uO** [lifenjoiner/wget-for-windows#7]
Win7x64 IE8已勾SSL2-3&TLS1-1.2
wget --no-check-certificate https://curl.se/windows/dl-8.8.0_3/curl-8.8.0_3-win64-mingw.zip
还是报请加'--no-check-certificate'
能否默认加'--no-check-certificate'以修复这个漏洞？顺便如有certificate相关功能也去了（就是验证是否安全相关的，强制判定为忽略不安全）

还有跪求编译x64

**Comment by lifenjoiner** [comment]
https://curl.se 被劫持了吗？我这边 IPv4 超时，IPv6 正常根本不需要加`--no-check-certificate`。

已测试：
`wget.exe -O nul https://expired.badssl.com/`返回失败，
`wget.exe -O nul --no-check-certificate https://expired.badssl.com/`返回正常。

> 强制判定为忽略不安全

这才是漏洞。


> 还有跪求编译x64

当前版本有问题没有解决，就没有上传，找找之前的版本，比如：
https://github.com/lifenjoiner/wget-for-windows/releases/tag/v1.21.4.187-965ae

**Comment by lifenjoiner** [comment]
贴出你的出错返回。

**Comment by 6uO** [comment]
网是移动运营商，只连了一个网不便切换排查
IE、谷歌浏览器正常，github.com/webfolderio/wget-windows有无--no-check-certificate都正常
就是您的出现问题
无--no-check-certificate
--2024-07-14 23:56:38--  https://curl.se/windows/dl-8.8.0_3/curl-8.8.0_3-win64-mingw.zip
Resolving curl.se... 2a04:4e42::347, 2a04:4e42:600::347, 2a04:4e42:c00::347, ...

Connecting to curl.se|2a04:4e42::347|:443... connected.
WinTLS: Certificate error: 0x80090326
WinTLS: To connect insecurely, use `--no-check-certificate'.
WinTLS: Handshake error: 0
WinTLS: ApplyControlToken failed: 0X80090301
Unable to establish SSL connection.

有--no-check-certificate
--2024-07-14 23:57:13--  https://curl.se/windows/dl-8.8.0_3/curl-8.8.0_3-win64-mingw.zip
Resolving curl.se... 2a04:4e42::347, 2a04:4e42:600::347, 2a04:4e42:c00::347, ...

Connecting to curl.se|2a04:4e42::347|:443... connected.
WinTLS: Certificate error: 0x80090326
WinTLS: To connect insecurely, use `--no-check-certificate'.
WinTLS: Handshake error: 0
WinTLS: ApplyControlToken failed: 0X80090301
Unable to establish SSL connection.
有无-O nul、IPv4/6也测试了，都同上请加--no-check-certificate报错

**Comment by 6uO** [comment]
`wget -O nul https://expired.badssl.com/`
--2024-07-15 00:22:10--  https://expired.badssl.com/
Resolving expired.badssl.com... 104.154.89.105
Connecting to expired.badssl.com|104.154.89.105|:443... connected.
WinTLS: Certificate error: SEC_E_CERT_EXPIRED
WinTLS: To connect insecurely, use `--no-check-certificate'.
WinTLS: Handshake error: 0
WinTLS: ApplyControlToken failed: 0X80090301
Unable to establish SSL connection.
`wget --no-check-certificate -O nul https://expired.badssl.com/`
--2024-07-15 00:22:11--  https://expired.badssl.com/
Resolving expired.badssl.com... 104.154.89.105
Connecting to expired.badssl.com|104.154.89.105|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 494 [text/html]
Saving to: 'nul'

nul                 100%[===================>]     494  --.-KB/s    in 0s
https://expired.badssl.com/就正常的很（

**Comment by 6uO** [comment]
感谢大佬耐心解答，建议顺便整理写在README（或起个FAQ.txt），感觉这个WinTLS问题比较重要（毕竟这个玩意出现验证层失败只会弹”请tm加--no-check-certificate“）
解决方法：升级OS、打补丁、网代软件

**Comment by lifenjoiner** [comment]
一个更便捷的分析工具：https://www.ssllabs.com/ssltest/

**Comment by 6uO** [comment]
膜拜
