### ISSUE TITLE
新版的--no-check-certificate 选项使用不了

### ISSUE THREAD

**Issue by rzhy1** [lifenjoiner/wget-for-windows#8]
新版的--no-check-certificate 选项使用不了，不加这个选项没法下载，加了之后不输出任何内容，直接没反应了。
比如：
wget https://expired.badssl.com显示结果如下：
--2024-07-20 11:02:03--  https://expired.badssl.com/
Resolving expired.badssl.com... 104.154.89.105
Connecting to expired.badssl.com|104.154.89.105|:443... connected.
WinTLS: handshake error: SEC_E_CERT_EXPIRED
WinTLS: To connect insecurely, try `--no-check-certificate'.
WinTLS: Handshake error: 0
WinTLS: ApplyControlToken failed: 0X80090301
Unable to establish SSL connection.

wget --no-check-certificate https://expired.badssl.com无任何显示。

以上问题在之前的版本（大小654K）中就没有。

**Comment by lifenjoiner** [comment]
感谢反馈。已修复：https://github.com/lifenjoiner/wget-for-windows/commit/e0033892e97bd23c7341e1a7577e6208715c9520 。

BTW：`wget -V`会显示具体版本号。

**Comment by rzhy1** [comment]
https://github.com/rockdaboot/wget2
wget2时多线程的，能否实现启用wintls的版本。使用中发现在Windows系统中使用启用wintls的有关下载工具，连接与下载速度明显要快一点。
